In [1]:
import torch
torch.empty(5,3)

tensor([[1.0102e-38, 1.0561e-38, 1.0102e-38],
        [1.0745e-38, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38]])

In [2]:
torch.rand(5,3)

tensor([[0.9475, 0.1528, 0.5060],
        [0.8430, 0.4326, 0.8979],
        [0.5237, 0.3250, 0.5427],
        [0.8911, 0.3885, 0.5260],
        [0.7996, 0.5652, 0.9372]])

In [3]:
torch.zeros(5,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
x = torch.tensor([5,3,99,0.5])
print(x)

tensor([ 5.0000,  3.0000, 99.0000,  0.5000])


In [5]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
y = torch.randn_like(x,dtype=torch.double)
print(y)

tensor([[-2.3015, -0.6637, -1.4250],
        [-0.6165, -1.0941,  0.7396],
        [-0.8865, -1.8372,  0.8401],
        [-1.2125,  0.5545,  1.4921],
        [-0.5670, -1.0067,  0.5093]], dtype=torch.float64)


In [7]:
print(x+y)
print(torch.add(x,y))

tensor([[-1.3015,  0.3363, -0.4250],
        [ 0.3835, -0.0941,  1.7396],
        [ 0.1135, -0.8372,  1.8401],
        [-0.2125,  1.5545,  2.4921],
        [ 0.4330, -0.0067,  1.5093]], dtype=torch.float64)
tensor([[-1.3015,  0.3363, -0.4250],
        [ 0.3835, -0.0941,  1.7396],
        [ 0.1135, -0.8372,  1.8401],
        [-0.2125,  1.5545,  2.4921],
        [ 0.4330, -0.0067,  1.5093]], dtype=torch.float64)


In [8]:
y.add(x)
print(y)

tensor([[-2.3015, -0.6637, -1.4250],
        [-0.6165, -1.0941,  0.7396],
        [-0.8865, -1.8372,  0.8401],
        [-1.2125,  0.5545,  1.4921],
        [-0.5670, -1.0067,  0.5093]], dtype=torch.float64)


In [9]:
y.add_(x)
print(y)

tensor([[-1.3015,  0.3363, -0.4250],
        [ 0.3835, -0.0941,  1.7396],
        [ 0.1135, -0.8372,  1.8401],
        [-0.2125,  1.5545,  2.4921],
        [ 0.4330, -0.0067,  1.5093]], dtype=torch.float64)


In [10]:
print(y[:,1])

tensor([ 0.3363, -0.0941, -0.8372,  1.5545, -0.0067], dtype=torch.float64)


In [11]:
x = torch.tensor([[5,3,1],[1,1,1]])
y = torch.tensor([1,2,1])
z = x*y
print(x*y)

tensor([[5, 6, 1],
        [1, 2, 1]])


In [12]:
print(z)
# -1為自動調整 
z.view(-1,1)

tensor([[5, 6, 1],
        [1, 2, 1]])


tensor([[5],
        [6],
        [1],
        [1],
        [2],
        [1]])

In [13]:
a = torch.tensor([5])
a.item()

5

In [14]:
print(z)


tensor([[5, 6, 1],
        [1, 2, 1]])


In [15]:
import numpy as np
print(type(z.numpy()))

<class 'numpy.ndarray'>


In [16]:
a = np.array([5,3])
a
t = torch.from_numpy(a)
t

tensor([5, 3], dtype=torch.int32)

In [17]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[6, 4, 2],
        [2, 2, 2]], device='cuda:0')
tensor([[6., 4., 2.],
        [2., 2., 2.]], dtype=torch.float64)


In [18]:
# * 是entry wise multiplication
# mm() 是矩陣乘法


import torch
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.tensor([[2,2,2],[3,3,3],[4,4,4]])
z = torch.tensor([[1,1,1],[1,1,1],[1,1,1]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [19]:
print(x.t())

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [20]:
print(y)

tensor([[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


In [21]:
print(y*x)
print(y)
print(y.mm(x))

tensor([[ 2,  4,  6],
        [12, 15, 18],
        [28, 32, 36]])
tensor([[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor([[24, 30, 36],
        [36, 45, 54],
        [48, 60, 72]])


In [22]:
print(x*z)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [23]:
print(x)
z = torch.tensor([1,1,1,2,2,2,3,3,3]).view(3,3)
print(z)
print(x.mm(z))


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[14, 14, 14],
        [32, 32, 32],
        [50, 50, 50]])


In [24]:
x = x.mm(z)
z[x>14]=-1
z

tensor([[ 1,  1,  1],
        [-1, -1, -1],
        [-1, -1, -1]])

In [25]:
z[z>0]=87
z

tensor([[87, 87, 87],
        [-1, -1, -1],
        [-1, -1, -1]])

In [26]:
import torch
dh = 4
de = 3
dq = 2

w1 = torch.randn(dh,de)
print(w1)
w2 = torch.randn(dh,dq)
xi = torch.randn(de,1)
print(xi)
q = torch.empty(dq,1)
t1 = w1.mm(xi)
t1.size()


tensor([[-1.3425,  0.0321,  1.3856],
        [-1.0324, -1.1790, -0.0083],
        [-0.5454, -0.0872, -0.9173],
        [ 1.4132,  0.9051,  0.5186]])
tensor([[ 1.3794],
        [ 1.3588],
        [-0.7983]])


torch.Size([4, 1])

In [27]:
xx = torch.randn(dh,1)
xx

tensor([[ 2.5732],
        [-0.7404],
        [-1.1165],
        [ 2.4615]])

In [28]:
print(w1*xx)

tensor([[-3.4546,  0.0825,  3.5654],
        [ 0.7644,  0.8730,  0.0061],
        [ 0.6089,  0.0974,  1.0241],
        [ 3.4785,  2.2280,  1.2766]])


In [30]:

de = 5
r = 4
torch.randn(50)

tensor([-1.1380,  0.6283, -0.4071,  2.4766, -1.3782,  2.7564,  0.5291,  1.1473,
        -0.0889,  1.4081,  0.1812, -0.1170,  0.3756,  0.7058, -1.1269, -1.3371,
         0.3343,  0.6020,  0.6805,  0.5914,  1.4914, -0.8243, -0.5879,  0.1901,
         1.2892,  0.8645, -1.7776, -0.3855,  0.9710,  0.6692, -1.1836,  0.2624,
         1.7526,  0.9901,  1.1166, -1.6275,  0.1099,  0.4989, -0.0819, -0.6948,
         1.3842,  0.8696,  0.4410,  0.0683,  0.4758,  0.6024, -0.0425,  0.9112,
         0.5751,  1.0956])