In [1]:
from BertWordEmbeddingClass import bertWordEmbedding
a = bertWordEmbedding()


ModuleNotFoundError: No module named 'BertWordEmbeddingClass'

In [ ]:
text = 'hello guys'
b = a.word2vec(text)



In [ ]:
print(b[0][0],len(b[0][0]))

In [ ]:
print(b[0][1],len(b[0][1]))

In [ ]:
print(b[1],len(b[1]))

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

In [3]:
n = 3
a = torch.ones(n,7)
b = torch.ones(n,7)

a = a.unsqueeze(-2)
b = b.unsqueeze(-3)

print(a,a.size())
print(b,b.size())
c = a+b
print(c,c.size())

tensor([[[1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.]]]) torch.Size([3, 1, 7])
tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]]) torch.Size([1, 3, 7])
tensor([[[2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2.]]]) torch.Size([3, 3, 7])


In [4]:
a.narrow(-3,0,a.size(-3))


tensor([[[1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.]]])

In [5]:
m = 2
r = 2

a = torch.ones([m,r,4])
a = a.unsqueeze(-2)
print(a)
print(a.shape)

b = torch.randn([m,r,4])
b = b.unsqueeze(-3)
print(b)
print(b.shape)

c = a+b
print(c)
print(c.shape)

d = c.narrow(-3,0,c.size(-3)-1)
print(d,d.shape)


tensor([[[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]]])
torch.Size([2, 2, 1, 4])
tensor([[[[-0.9120,  0.6662,  0.2485, -0.5008],
          [-0.6271, -0.7371, -0.2447, -0.2818]]],


        [[[-1.5309, -0.0416,  0.1012, -0.7087],
          [-0.4677, -1.0013,  0.8521,  0.9323]]]])
torch.Size([2, 1, 2, 4])
tensor([[[[ 8.7961e-02,  1.6662e+00,  1.2485e+00,  4.9923e-01],
          [ 3.7292e-01,  2.6291e-01,  7.5527e-01,  7.1815e-01]],

         [[ 8.7961e-02,  1.6662e+00,  1.2485e+00,  4.9923e-01],
          [ 3.7292e-01,  2.6291e-01,  7.5527e-01,  7.1815e-01]]],


        [[[-5.3094e-01,  9.5844e-01,  1.1012e+00,  2.9128e-01],
          [ 5.3225e-01, -1.3115e-03,  1.8521e+00,  1.9323e+00]],

         [[-5.3094e-01,  9.5844e-01,  1.1012e+00,  2.9128e-01],
          [ 5.3225e-01, -1.3115e-03,  1.8521e+00,  1.9323e+00]]]])
torch.Size([2, 2, 2, 4])
tensor([[[[ 8.7961e-02,  1.6662e+00,  1.2485e+00,  4.9923e-01],
          [ 3.72

In [6]:
a = [1,3,5,7]
b = [6,0,3,1]
c = [1,2,5,3]
d = [7,0,3,8]

x = torch.tensor([[a],[b]])
y = torch.tensor([[c,d]])
z = x+y
print(z)

tensor([[[ 2,  5, 10, 10],
         [ 8,  3,  8, 15]],

        [[ 7,  2,  8,  4],
         [13,  0,  6,  9]]])


In [7]:
x = torch.tensor([1,2,3])
y = torch.tensor([[1,1,1],[2,2,2]])
print(x+y)

tensor([[2, 3, 4],
        [3, 4, 5]])


# token to token matrix

In [10]:
x= torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

y = b+x
y

tensor([[ 6,  8],
        [10, 12]])

# Padding code

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

# (batch, (block_num), seq_len, 1, word_dim)

#each block has 7
r = 7 
# sequence length is 12
n = 12 
pad_len = (r - n % r) % r
print(n%r,'n%r')
print(pad_len,'padlength')

# x: (batch, seq_len, word_dim)
x = torch.randn((1,n,4))
print(x,x.size())

pad = Variable( torch.zeros(x.size(0), pad_len, x.size(2)) )
print(pad,pad.shape)
            # pagging at sequence length
x = torch.cat([x,pad] , dim=1)
x = torch.stack([x.narrow(1, i, r) for i in range(0, x.size(1), r)], dim=1)
print(x,x.shape)

5 n%r
2 padlength
tensor([[[-0.6781, -0.8046,  0.4035, -2.0628],
         [-1.1711, -0.7755, -0.1900,  0.5988],
         [ 0.5550,  0.4338,  0.3972, -1.0895],
         [ 0.6061,  0.7963,  0.6307, -1.2075],
         [-2.5939,  0.7333,  0.2214, -0.8371],
         [ 0.4096, -0.3041,  0.1892,  0.9477],
         [-0.0943, -1.0447,  2.9666, -0.5854],
         [ 0.7739,  0.8078, -1.7294,  0.3237],
         [-0.2387,  0.9505, -0.0283, -1.5386],
         [-1.0475,  1.9504, -1.9491, -1.2906],
         [-0.3331,  0.9963, -0.7191,  0.9172],
         [ 0.1990, -0.7253, -0.7015,  0.2782]]]) torch.Size([1, 12, 4])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) torch.Size([1, 2, 4])
tensor([[[[-0.6781, -0.8046,  0.4035, -2.0628],
          [-1.1711, -0.7755, -0.1900,  0.5988],
          [ 0.5550,  0.4338,  0.3972, -1.0895],
          [ 0.6061,  0.7963,  0.6307, -1.2075],
          [-2.5939,  0.7333,  0.2214, -0.8371],
          [ 0.4096, -0.3041,  0.1892,  0.9477],
          [-0.0943, -1.0447

# 1-G

In [8]:
import torch
x = torch.randn((3,3))
print(x)
print(1-x)

tensor([[-1.1003, -0.3859,  1.1896],
        [ 0.7929,  1.3297,  1.2588],
        [-0.7200, -0.7254, -0.7781]])
tensor([[ 2.1003,  1.3859, -0.1896],
        [ 0.2071, -0.3297, -0.2588],
        [ 1.7200,  1.7254,  1.7781]])


In [10]:
x = torch.randn((3,3))
print(x,x.shape)
y = torch.randn((3,3))
print(y,y.shape)
z = torch.stack([x,y],dim=1)
print(z,z.shape)

tensor([[-0.5192, -0.2507,  1.2637],
        [ 1.2450, -0.9896,  1.4295],
        [ 1.2420,  1.8667,  0.8840]]) torch.Size([3, 3])
tensor([[-0.2739, -0.4443, -0.1571],
        [ 0.8800, -0.3953,  0.3116],
        [-1.1060,  1.2349, -0.9325]]) torch.Size([3, 3])
tensor([[[-0.5192, -0.2507,  1.2637],
         [-0.2739, -0.4443, -0.1571]],

        [[ 1.2450, -0.9896,  1.4295],
         [ 0.8800, -0.3953,  0.3116]],

        [[ 1.2420,  1.8667,  0.8840],
         [-1.1060,  1.2349, -0.9325]]]) torch.Size([3, 2, 3])


# test view

In [18]:
import torch
x = torch.randn(4,3,2)
print(x)
y = x.view(x.size(0),-1,x.size(-1)).narrow(1,0,3)
y

tensor([[[ 0.3738,  0.9322],
         [ 1.0129,  0.5007],
         [-1.1390, -1.4260]],

        [[ 0.1444, -0.0541],
         [-0.6387, -0.5478],
         [-0.3588,  0.7729]],

        [[ 0.7434, -2.1836],
         [-0.3162,  1.6284],
         [-0.4825, -1.0646]],

        [[-0.8810,  1.5524],
         [-0.3042,  0.3273],
         [ 0.9063,  0.3734]]])


tensor([[[ 0.3738,  0.9322],
         [ 1.0129,  0.5007],
         [-1.1390, -1.4260]],

        [[ 0.1444, -0.0541],
         [-0.6387, -0.5478],
         [-0.3588,  0.7729]],

        [[ 0.7434, -2.1836],
         [-0.3162,  1.6284],
         [-0.4825, -1.0646]],

        [[-0.8810,  1.5524],
         [-0.3042,  0.3273],
         [ 0.9063,  0.3734]]])